    pipeline {
  agent any
  stages {
    stage('Checkout') {
      steps {
        git 'https://github.com/your/repo'
      }
    }
    stage('Build Docker Images') {
      steps {
        sh 'docker-compose build'
      }
    }
    stage('Deploy') {
      steps {
        sh 'docker-compose up -d'
      }
    }
  }
}
